### ISSUE TITLE
Why is the output different every time

### ISSUE THREAD

**Issue by fsted** [frgfm/torch-cam#119]
hi,this code is great,but i meet a Strange appearance
I set the model to eval and then use the example  given, but I find that the output of the same photo is different every time.
how can i do it , thanks :)

**Comment by fsted** [comment]
Just now I loaded my own weight file. Later,  now I let pre trained = true. After changing to the official weight file, the output was stable. What a strange thing...

**Comment by frgfm** [comment]
Hi @fsted :wave: 

It's quite hard for me to answer this without any code snippet :sweat_smile: Mind sharing a bit more information for me to reproduce this behaviour?

My guess would be that you're using a CAM method that involves a noisy process (`SSCAM` & `SmoothGradCAMpp` involve random variable sampling for the CAM computation for instance) :point_up:

**Comment by fsted** [comment]
> Hi @fsted 👋
> 
> It's quite hard for me to answer this without any code snippet 😅 Mind sharing a bit more information for me to reproduce this behaviour?
> 
> My guess would be that you're using a CAM method that involves a noisy process (`SSCAM` & `SmoothGradCAMpp` involve random variable sampling for the CAM computation for instance) ☝️

Thanks, I found the reason,It's indeed SSCAM...
