### ISSUE TITLE
Add a `conda` install option for `torchcam`

### ISSUE THREAD

**Issue by sugatoray** [frgfm/torch-cam#125]
### 🚀 Feature

A conda install option could be very helpful. Preferably, if it is on `conda-forge` channel. I have already started the work (PR: https://github.com/conda-forge/staged-recipes/pull/17307). Once the PR is merged, you will be able to install `torchcam` as:

```sh
conda install -c conda-forge torchcam
```

> I will post updates once the PR is merged here in this issue.

**Comment by sugatoray** [comment]
**Note:**

At present there is an option to install `torchcam` using conda (but it NOT on `conda-forge` channel).

- https://anaconda.org/frgfm/torchcam

```sh
conda install -c frgfm torchcam
```

**Comment by frgfm** [comment]
Hi @sugatoray :wave:

As you mentioned, there is already an option to install from my personal anaconda cloud channel. I must admit I don't really see the need of having it in conda-forge?

For complex environments with multiple packages, you always add several conda channels anyway :man_shrugging:

**Comment by sugatoray** [comment]
Hi @frgfm,

If you add another library to `conda-forge`, which uses `torchcam` as a dependency, then it will be necessary to create a complete package on conda-forge. This is why, even though pytorch is maintained on `pytorch` channel, it also exists on `conda-forge` channel.

So, adding `torchcam` to conda-forge will pave way for downstream applications/libraries to get onboarded on `conda-forge`.

**Comment by sugatoray** [comment]
## Update :sparkles: :rocket:

The PR was just merged and `torchcam` is now available on `conda-forge`. Please give it 2-3 hours before it becomes downloadable.

cc: @frgfm 

![image](https://user-images.githubusercontent.com/10201242/147281198-dcb2b2cf-9159-4f12-af5c-7f4923e80360.png)

**Comment by frgfm** [comment]
I forgot to answer, but thank you for your hard work @sugatoray :pray:
