### ISSUE TITLE
Issue when visualizing with xception network

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [frgfm/torch-cam#126]
### Bug description

I have a varient of xception model which has only 2 classes in final layer. When I use this library with the model it only works with CAM and not with other activation map models. 

### Code snippet to reproduce the bug

This is the network i use [link](https://github.com/HongguLiu/Deepfake-Detection/tree/master/network) . Similar error can be seen in some models in [Hugging Face](https://huggingface.co/spaces/frgfm/torch-cam)
![image](https://user-images.githubusercontent.com/38417165/147276007-acf7fb60-d540-4ed8-b794-f14de814ce6e.png)

### Error traceback

` File "cam.py", line 34, in <module>
    activation_map = cam_extractor(out.squeeze(0).argmax().item(), out)
  File "/hdd/2017CS128/.conda/envs/env_pytorch/lib/python3.6/site-packages/torchcam/methods/core.py", line 143, in __call__
    return self.compute_cams(class_idx, scores, normalized)
  File "/hdd/2017CS128/.conda/envs/env_pytorch/lib/python3.6/site-packages/torchcam/methods/core.py", line 158, in compute_cams
    weights = self._get_weights(class_idx, scores)
  File "/hdd/2017CS128/.conda/envs/env_pytorch/lib/python3.6/site-packages/torchcam/methods/gradient.py", line 280, in _get_weights
    grad_2 = [g2.add_(grad.pow(2)) for g2, grad in zip(grad_2, self.hook_g)]
  File "/hdd/2017CS128/.conda/envs/env_pytorch/lib/python3.6/site-packages/torchcam/methods/gradient.py", line 280, in <listcomp>
    grad_2 = [g2.add_(grad.pow(2)) for g2, grad in zip(grad_2, self.hook_g)]
RuntimeError: The size of tensor a (10) must match the size of tensor b (149) at non-singleton dimension 3`

### Environment

ubuntu 18.4
CUDA Version: 11.2

**Comment by frgfm** [comment]
Hello @AnjanaSamindraPerera :wave: 

Thanks for reporting this, the answer is rather simple:
- the base CAM method is the oldest one and the most containing: it only works with models that have global average pooling, and a single fully connected (or conv1x1) layer for the classification.
- MobileNetV3 has 2 fully connected layers in its classification head, so it cannot work

I suggest checking other methods if you want to focus on that architecture :)
I hope this helps!
