### ISSUE TITLE
 VGG16 can't assist with plain CAM?

### ISSUE THREAD

**Issue by liuyx599** [frgfm/torch-cam#153]
### Bug description

hi~  
I followed your Quick Tour, and I chose the **plain CAM**  and **VGG16**, but an error occured

Only the line 6 and lin 7 are different from you Quick Tour

But When I chose **plain CAM** with **Resnet18**， it went well

### Code snippet to reproduce the bug

```python
from torchvision.io.image import read_image
from torchvision.transforms.functional import normalize, resize, to_pil_image
from torchvision.models import resnet18,vgg16
from torchcam.methods import SmoothGradCAMpp, CAM

model = vgg16(pretrained=True).eval()   #   The first place differs to Quick Tour    just resnet => vgg
cam_extractor = CAM(model)  #    The second place differs to Quick Tour    just SmoothGradCAMpp => CAM

img = read_image("./datasets/barracouta.JPEG")

input_tensor = normalize(resize(img, (224, 224)) / 255., [0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
out = model(input_tensor.unsqueeze(0))


activation_map = cam_extractor(out.squeeze(0).argmax().item(), out)
```

### Error traceback

```
The size of tensor a (25088) must match the size of tensor b (512) at non-singleton dimension 0

in <module>
    activation_map = cam_extractor(out.squeeze(0).argmax().item(), out)
```

### Environment

I run it in jupyter as the same as you Quick Tour

**Comment by frgfm** [comment]
Hello @liuyx599 👋

Yes, so plain CAMs were the first iterations and only work with models that have global average pooling and a single fully connected layer 👌

It's the fastest method but the most constraining one as well 😅

The result is inferior to other CAM methods so I'd suggest switching to another if you are using a VGG 🙂

You can refer to the initial paper for more details or let me know if you have any questions!

Cheers ✌️

**Comment by liuyx599** [comment]
ooook, I get it!  thank u very much and wish u a happy life!
