### ISSUE TITLE
Video Models

### ISSUE THREAD

**Issue by kamalesh0406** [frgfm/torch-cam#17]
Hi can we use this library to use GRAD-CAM on 3D CNN models?

**Comment by frgfm** [comment]
Hi there @kamalesh0406,

The visualization script is not adapted for 3D tensors, as they can't be mapped to PIL images. But the CAM extractor itself is compatible yes. Here is a small example:
```
import torch
import torch.nn as nn
from torchcam.cams import SmoothGradCAMpp

# Define a 3D CNN model
model = nn.Sequential(
    nn.Conv3d(3, 8, 3, 1),
    nn.BatchNorm3d(8),
    nn.LeakyReLU(0.1),
    nn.MaxPool3d(2),
    nn.Conv3d(8, 16, 3, 1),
    nn.BatchNorm3d(16),
    nn.LeakyReLU(0.1),
    nn.AdaptiveAvgPool3d(1),
    nn.Flatten(1),
    nn.Linear(16, 2))

input_t = torch.rand((1, 3, 32, 32, 32))
# Parametrize the CAM extractor
extractor = SmoothGradCAMpp(model, '6', '0')
scores = model(input_t)
class_idx = scores.squeeze(0).argmax().item()
activation_map = extractor(class_idx, scores).cpu()
extractor.clear_hooks()
print(activation_map.shape)
```

which yields:
```
torch.Size([13, 13, 13])
```

I would advise against using CAM methods that are computationally intensive with 3D CNN depending on your system specs (Score CAM & SS CAM for instance).


If you feel like submitting a PR to add a visualization option, I'd be happy to look into it :+1: 
Let me know if that helped, cheers!

**Comment by kamalesh0406** [comment]
Yup this helps thanks!

**Comment by frgfm** [comment]
Glad it helped @kamalesh0406!
I'll close the issue then, feel free to reopen if you get some troubles along the way :ok_hand:
