### ISSUE TITLE
conda install issue

### ISSUE THREAD

**Issue by wuliytTaotao** [frgfm/torch-cam#27]
When I install torchcam via `conda install -c frgfm torchcam`, the verison of pytorch will be downgraded into 1.4 .

My pytorch version is 1.6.

**Comment by frgfm** [comment]
Hi there @wuliytTaotao :wave: 

Thanks for reporting this. I actually had to put an upper bound in the conda recipe (https://github.com/frgfm/torch-cam/blob/master/.conda/meta.yaml#L22) to solve a build issue specific to conda back then.

But I'm gonna run some tests to check if I can remove this annoying constraint!

**Comment by frgfm** [comment]
The fix was just merged on master, I'll bump a new package release on pypi & conda shortly after tackling another issue!
Thanks again for reporting this, and let me know if you encounter other problems

**Comment by frgfm** [comment]
@wuliytTaotao the latest conda release was published just a few minutes ago ;)
