### ISSUE TITLE
torch 1.8.0+cu111 - UserWarning for non-full backward hook

### ISSUE THREAD

**Issue by FredrikM97** [frgfm/torch-cam#48]
torch: '1.8.0+cu111'
Python: 3.9

Getting the following warning:
```
/lib/python3.9/site-packages/torch/nn/modules/module.py:795: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
```

Might be something to keep an eye for to prevent future errors? :)

**Comment by frgfm** [comment]
Haha I happen to have read the full release note the day it was published and thought that I would have to update all of those :)
However, if I'm not mistaking, this is not backward compatible. So I'll wait a bit for users to mainly use pytorch >= 1.8.0

But good catch :ok_hand:

**Comment by FredrikM97** [comment]
I see! Think I read something about that as well. Maybe place an ignore for the warning/one time error? If a user update to pytorch 1.8 the log is spammed each time a CAM is called.

**Comment by FredrikM97** [comment]
Sure! I can take a look into it when I have some free time :)
