### ISSUE TITLE
package conflicts

### ISSUE THREAD

**Issue by MercuialC** [frgfm/torch-cam#57]
When I use pytorch 1.6, there are a lot of package conflicts when installing torchcam, how can I solve it?
Thank u.

**Comment by frgfm** [comment]
Hi @MercuialC,

I might have to increase the pytorch version constraints on the package. Could you be more specific please? I cannot do much without more information :sweat_smile: 

How did you install torchcam? What are the conflicts? etc. (cf. the bug report template)

**Comment by MercuialC** [comment]
thank you for your reply
I installed torchcam via conda
When I run the example, torchvision can't find it, and ImportError: DLL load failed:
I tried to install the 1.6.0 version of pytorch through the command: conda install pytorch==1.6.0 torchvision==0.7.0 -c pytorch
Some error messages are as follows：
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining sip:  10%|██████▌                                                             | 5/52 [00:04<00:43,  1.07it/s]-Examining freetype:  17%|██████████▉                                                    | 9/52 [00:08<00:34,  1.23it/s]\Examining cffi:  27%|█████████████████▊                                                | 14/52 [00:18<00:52,  1.38s/it]\Examining matplotlib-base:  56%|██████████████████████████████▋                        | 29/52 [00:37<00:24,  1.05s/it]-Examining pycparser:  81%|█████████████████████████████████████████████████▎           | 42/52 [00:52<00:09,  1.10it/s]-Examining conflict for kiwisolver mkl-service numpy-base pytorch sip wheel pip cffi openssl torchvision tornado pyqt nu-Examining conflict for kiwisolver mkl-service numpy-base pytorch sip wheel pip cffi torchvision tornado pyqt numpy olef\Examining conflict for kiwisolver jpeg mkl-service numpy-base pytorch sip vs2015_runtime tk wheel freetype pip cffi ope|Examining conflict for torchvision torchcam matplotlib-base mkl-service numpy-base mkl_fft pytorch numpy matplotlib mkl/Examining conflict for matplotlib-base cycler tornado mkl-service numpy-base mkl_fft matplotlib pytorch numpy six pytho|Examining conflict for torchvision torchcam matplotlib-base mkl-service numpy-base mkl_fft blas pytorch numpy matplotli/Examining conflict for torchcam matplotlib-base matplotlib setuptools numpy python wheel pip:  60%|▌| 31/52 [00:35<00:0|Examining conflict for matplotlib-base matplotlib setuptools wincertstore wheel pip:  60%|▌| 31/52 [00:36<00:08,  2.57i\Examining conflict for pillow torchcam matplotlib-base qt pyqt libpng freetype matplotlib:  67%|▋| 35/52 [00:39<00:12, \Examining conflict for python pip:  73%|██████████████████████████████████▎            | 38/52 [00:41<00:11,  1.18it/s]|Examining conflict for pillow torchvision torchcam matplotlib-base matplotlib:  79%|██▎| 41/52 [00:43<00:07,  1.48it/s]|Examining conflict for torchcam matplotlib pyqt:  88%|█████████████████████████████▏   | 46/52 [00:47<00:05,  1.16it/s]\Examining conflict for pillow qt zstd xz libtiff:  94%|██████████████████████████████▏ | 49/52 [00:48<00:02,  1.44it/s]\Examining conflict for torchcam matplotlib-base matplotlib: : 53it [00:49,  2.09it/s]                                  -failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - cycler -> python[version='2.6.*|3.3.*']
  - mkl-service -> python[version='2.6.*|3.3.*']
  - python-dateutil -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - wheel -> python[version='2.6.*|>=3.9,<3.10.0a0']

Your python: python==3.6.5

**Comment by frgfm** [comment]
> When I run the example, torchvision can't find it, and ImportError: DLL load failed:

What do you mean by this?

Regarding the conflict issue, have you tried to install pytorch or torchvision using conda recently? 
Because as you can see [here](https://github.com/frgfm/torch-cam/blob/master/setup.py#L43-L46), the requirements for torchcam are pretty loose. The conflicts look like they are referring to your python version and pytorch/torchvision dependencies.

**Comment by frgfm** [comment]
Any update @MercuialC ?

**Comment by frgfm** [comment]
Hi @MercuialC :wave: 

Apart from if you have new details about this issue, I doubt this is due to this repo considering the very loose requirements. I'm closing this issue for now, feel free to reopen if there is something new coming up!
