### ISSUE TITLE
How can I use cam to train my model?

### ISSUE THREAD

**Issue by sunyue11** [frgfm/torch-cam#65]
## 🚀 Feature

In the cam_example.py file, the cam only be used as visualization. So how can I use the cam to train my model to get the discriminative part in image just like  "Learning Deep Features for Discriminative Localization" says.

**Comment by frgfm** [comment]
Hi @sunyue11 :wave: 

Could you be more specific? I'm not sure I understand your question:
- in the paper, they present the method which is implemented in this library, that takes a pretrained classification model and produces the CAM, which can, in turn, be considered as a localization cue.
- so to the best of my understanding, the author is not suggesting using CAMs to train a model. You have to use trained models to get interesting CAM results.

Let me know if I didn't get your point!

**Comment by sunyue11** [comment]
Thank you so much for your reply! Actually you have answered my question!!
